import { Project, Service, Testimonial, BlogPost, FAQ } from './types'

// Local images
const IMG = (n: string) => `/images/${n}`

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Lakeview Resort & Spa',
    slug: 'lakeview-resort',
    image: IMG('image07.jpeg'),
    gallery: [IMG('image07.jpeg'), IMG('image08.jpeg'), IMG('image09.jpeg')],
    description: 'Complete redesign of a 12-acre lakeside resort with tropical gardens and water features',
    fullDescription: 'A comprehensive redesign of Lakeview Resort, transforming the property into a tropical paradise. The project included master planning, hardscaping, softscaping, water feature design, and outdoor lighting. The result is a harmonious blend of luxury and nature that has become a benchmark for resort design in Bangladesh.',
    location: 'Sylhet, Bangladesh',
    category: 'resort',
    area: '12 acres',
    year: '2024',
    highlights: ['Tropical Garden Design', 'Infinity Pool Landscape', 'Water Feature Design', 'Outdoor Lighting'],
  },
  {
    id: '2',
    title: 'Green Terrace Garden',
    slug: 'green-terrace-garden',
    image: IMG('image10.jpeg'),
    gallery: [IMG('image10.jpeg'), IMG('image11.jpeg'), IMG('image12.jpeg')],
    description: 'Rooftop garden transformation creating an urban oasis in the heart of the city',
    fullDescription: 'An innovative rooftop garden design in downtown Dhaka, featuring native Bangladeshi flora, sustainable irrigation systems, and multifunctional recreational spaces. This project demonstrates how urban spaces can be transformed into green sanctuaries.',
    location: 'Gulshan, Dhaka',
    category: 'rooftop',
    area: '2 acres',
    year: '2023',
    highlights: ['Rooftop Landscape', 'Sustainable Irrigation', 'Native Flora', 'Recreational Zones'],
  },
  {
    id: '3',
    title: 'Botanical Garden Retreat',
    slug: 'botanical-garden-retreat',
    image: IMG('image13.jpeg'),
    gallery: [IMG('image13.jpeg'), IMG('image14.jpeg'), IMG('image15.jpeg')],
    description: 'Design of a botanical garden retreat with curated plant collections and meditation spaces',
    fullDescription: 'A serene botanical garden retreat designed for wellness and contemplation. Features include themed garden rooms, a meditation pavilion, water gardens, and a greenhouse showcasing rare Bangladeshi plant species. The design emphasizes biodiversity and environmental education.',
    location: 'Cox\'s Bazar, Bangladesh',
    category: 'garden',
    area: '8 acres',
    year: '2023',
    highlights: ['Themed Garden Rooms', 'Meditation Pavilion', 'Water Gardens', 'Rare Species Collection'],
  },
  {
    id: '4',
    title: 'Sky Garden Residences',
    slug: 'sky-garden-residences',
    image: IMG('image16.jpeg'),
    gallery: [IMG('image16.jpeg'), IMG('image17.jpeg'), IMG('image18.jpeg')],
    description: 'Landscape design for premium residential complex with sky gardens and green corridors',
    fullDescription: 'A premium residential landscape project featuring interconnected sky gardens, green corridors, and community spaces. The design creates a seamless flow between indoor and outdoor living, setting a new standard for urban residential landscape architecture in Bangladesh.',
    location: 'Banani, Dhaka',
    category: 'commercial',
    area: '5 acres',
    year: '2024',
    highlights: ['Sky Gardens', 'Green Corridors', 'Community Spaces', 'Indoor-Outdoor Flow'],
  },
  {
    id: '5',
    title: 'Coastal Paradise Resort',
    slug: 'coastal-paradise-resort',
    image: IMG('image19.jpeg'),
    gallery: [IMG('image19.jpeg'), IMG('image20.jpeg'), IMG('image21.jpeg')],
    description: 'Beachfront resort landscaping with coastal gardens, pools, and outdoor entertainment zones',
    fullDescription: 'A stunning beachfront resort landscape design that embraces the coastal environment. The project includes salt-tolerant gardens, infinity pools overlooking the sea, outdoor dining pavilions, and a beach club. Every element celebrates the natural beauty of Bangladesh\'s coastline.',
    location: 'Saint Martin\'s Island, Bangladesh',
    category: 'resort',
    area: '15 acres',
    year: '2022',
    highlights: ['Beachfront Design', 'Salt-Tolerant Gardens', 'Infinity Pools', 'Beach Club'],
  },
  {
    id: '6',
    title: 'Urban Park & Recreation',
    slug: 'urban-park-recreation',
    image: IMG('image22.jpeg'),
    gallery: [IMG('image22.jpeg'), IMG('image23.jpeg'), IMG('image24.jpeg')],
    description: 'Public park design with recreational facilities, walking trails, and community gathering spaces',
    fullDescription: 'A community-focused urban park design that brings nature back to the city. Features include extensive walking and cycling trails, children\'s play areas, outdoor fitness zones, amphitheater, and native plant gardens. The park has become a beloved community hub.',
    location: 'Uttara, Dhaka',
    category: 'park',
    area: '20 acres',
    year: '2022',
    highlights: ['Walking Trails', 'Children\'s Play Areas', 'Open-Air Amphitheater', 'Community Gardens'],
  },
]

export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Resort & Hotel Design',
    description: 'Complete landscape architecture for luxury resorts, boutique hotels, and hospitality properties across Bangladesh.',
    icon: '🌴',
  },
  {
    id: '2',
    title: 'Park & Garden Design',
    description: 'Creating public parks, botanical gardens, and private garden sanctuaries that celebrate Bangladesh\'s natural beauty.',
    icon: '🌿',
  },
  {
    id: '3',
    title: 'Rooftop & Terrace Gardens',
    description: 'Transforming urban rooftops into lush green spaces with sustainable design and native plantings.',
    icon: '🏗️',
  },
  {
    id: '4',
    title: 'Redesign & Renovation',
    description: 'Breathing new life into existing properties with thoughtful landscape redesign and modern amenities.',
    icon: '🔄',
  },
  {
    id: '5',
    title: 'Master Planning',
    description: 'Comprehensive site planning and conceptual design for large-scale resort and recreational developments.',
    icon: '📐',
  },
  {
    id: '6',
    title: 'Consultation & Advisory',
    description: 'Expert guidance on plant selection, sustainable practices, irrigation, and landscape maintenance.',
    icon: '🤝',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Art of Resort Landscape Design in Bangladesh',
    slug: 'art-of-resort-landscape',
    image: IMG('image25.jpeg'),
    excerpt: 'Exploring the unique challenges and opportunities of designing resort landscapes in the Bangladeshi climate.',
    content: 'Bangladesh offers a unique canvas for landscape architects...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-06-15',
    category: 'Design',
    readTime: 6,
    tags: ['Resort Design', 'Landscape', 'Bangladesh'],
  },
  {
    id: '2',
    title: 'Native Plants for Bangladeshi Landscapes',
    slug: 'native-plants-bangladesh',
    image: IMG('image07.jpeg'),
    excerpt: 'A guide to selecting and incorporating native Bangladeshi flora in modern landscape design.',
    content: 'Native plants are the backbone of sustainable landscape design...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-05-20',
    category: 'Gardening',
    readTime: 8,
    tags: ['Plants', 'Sustainability', 'Native Flora'],
  },
  {
    id: '3',
    title: 'Sustainable Practices in Tropical Landscape Design',
    slug: 'sustainable-tropical-design',
    image: IMG('image10.jpeg'),
    excerpt: 'How eco-friendly design principles are shaping the future of landscape architecture in Bangladesh.',
    content: 'Sustainability is no longer optional in landscape design...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-04-10',
    category: 'Sustainability',
    readTime: 7,
    tags: ['Sustainability', 'Eco-Friendly', 'Tropical Design'],
  },
  {
    id: '4',
    title: 'Transforming Urban Spaces: Rooftop Gardens in Dhaka',
    slug: 'rooftop-gardens-dhaka',
    image: IMG('image13.jpeg'),
    excerpt: 'How rooftop gardens are revolutionizing urban living in Bangladesh\'s capital city.',
    content: 'As Dhaka grows vertically, rooftop gardens offer a solution...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-03-05',
    category: 'Urban Design',
    readTime: 5,
    tags: ['Rooftop', 'Urban', 'Dhaka'],
  },
  {
    id: '5',
    title: 'Water Features in Bangladeshi Garden Design',
    slug: 'water-features-garden-design',
    image: IMG('image16.jpeg'),
    excerpt: 'The role of water in creating serene and visually stunning garden environments.',
    content: 'Water has always been central to Bangladeshi garden design...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-02-18',
    category: 'Design',
    readTime: 6,
    tags: ['Water Features', 'Garden Design', 'Serenity'],
  },
  {
    id: '6',
    title: 'The Future of Resort Architecture in Bangladesh',
    slug: 'future-resort-architecture',
    image: IMG('image19.jpeg'),
    excerpt: 'Trends and innovations shaping the next generation of resort design in Bangladesh.',
    content: 'Bangladesh\'s tourism sector is growing rapidly...',
    author: 'Rajdhani Design Team',
    publishedAt: '2024-01-22',
    category: 'Architecture',
    readTime: 7,
    tags: ['Architecture', 'Trends', 'Innovation'],
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Fahim Rahman',
    title: 'Owner, Lakeview Resort',
    image: 'https://i.pravatar.cc/150?u=fahim',
    content: 'The transformation of our resort exceeded all expectations. Our guests constantly compliment the stunning landscape design. Truly world-class work.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Sultana Ahmed',
    title: 'CEO, Green Terrace Holdings',
    image: 'https://i.pravatar.cc/150?u=sultana',
    content: 'Our rooftop garden has become the highlight of the building. The design perfectly balances aesthetics with functionality. Highly recommended.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Dr. Kabir Hossain',
    title: 'Director, Botanical Garden Retreat',
    image: 'https://i.pravatar.cc/150?u=kabir',
    content: 'An incredible vision brought to life. The themed gardens and meditation spaces are exquisite. A true sanctuary for nature lovers.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Nadia Islam',
    title: 'Developer, Sky Garden Residences',
    image: 'https://i.pravatar.cc/150?u=nadia',
    content: 'The sky gardens have become our flagship feature. The attention to detail and understanding of tropical landscapes is remarkable.',
    rating: 5,
  },
]

export const FAQS: FAQ[] = [
  {
    id: '1',
    question: 'What types of projects do you undertake?',
    answer: 'We specialize in landscape design and redesign for resorts, hotels, parks, gardens, rooftop spaces, and commercial properties across Bangladesh.',
    category: 'Services',
  },
  {
    id: '2',
    question: 'Do you work on projects outside of Dhaka?',
    answer: 'Yes, we work on projects throughout Bangladesh, including Sylhet, Cox\'s Bazar, Saint Martin\'s Island, and other regions.',
    category: 'Services',
  },
  {
    id: '3',
    question: 'What is the typical timeline for a project?',
    answer: 'Timelines vary based on scope. A typical resort landscape project takes 3-6 months, while smaller garden designs may take 4-8 weeks.',
    category: 'Process',
  },
  {
    id: '4',
    question: 'Do you use native Bangladeshi plants?',
    answer: 'Yes, we prioritize native Bangladeshi flora in our designs for sustainability, lower maintenance, and authentic local character.',
    category: 'Design',
  },
  {
    id: '5',
    question: 'Can you work with existing structures and landscapes?',
    answer: 'Absolutely. We specialize in redesigning and renovating existing properties, breathing new life into established spaces.',
    category: 'Services',
  },
  {
    id: '6',
    question: 'How do I get started with a project?',
    answer: 'Simply reach out through our contact form or call us. We\'ll schedule a consultation to understand your vision and provide a tailored proposal.',
    category: 'Process',
  },
]

export const CONTACT_INFO = {
  address: 'Banani, Dhaka 1213, Bangladesh',
  phone: '+880 1700-123-456',
  email: 'hello@rajdhanigarden.com',
  hours: {
    weekdays: '9:00 AM - 6:00 PM',
    saturday: '10:00 AM - 4:00 PM',
    sunday: 'Closed',
  },
  socialMedia: {
    youtube: 'https://youtube.com/@rajdhaniroopgarden',
    tiktok: 'https://tiktok.com/@rajdhaniroopgarden',
    instagram: 'https://www.instagram.com/rajdhaniroopgarden',
    facebook: 'https://www.facebook.com/RajdhaniRoopGarden',
  },
}

export const YOUTUBE_SHORTS = [
  { id: '_ogzRTmfbrY', title: 'Rajdhani Roop Garden Short 1' },
  { id: 'ppVPJaKIVac', title: 'Rajdhani Roop Garden Short 2' },
  { id: 'vpM3Q0iHT8M', title: 'Rajdhani Roop Garden Short 3' },
  { id: 'IlkSNvzIaeQ', title: 'Rajdhani Roop Garden Short 4' },
  { id: 'w7Yumcr4wRI', title: 'Rajdhani Roop Garden Short 5' },
]

export const STATS = {
  projectsCompleted: 50,
  yearsExperience: 12,
  resortsDesigned: 15,
  parksCreated: 20,
}
